import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 15,
    marginTop: 0,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.2)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  backIcon: {
    width: 24,
    height: 24,
  },
  backText: {
    fontSize: 24,
    fontWeight: '900',
    color: 'white',
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  title: {
    fontSize: 28,
    fontWeight: '900',
    color: 'white',
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  headerTitleContainer: {
    alignItems: 'center',
    flex: 1,
  },
  progressContainer: {
    backgroundColor: 'rgba(0,0,0,0.1)',
    width: 120,
    height: 14,
    borderRadius: 7,
    marginTop: 4,
    overflow: 'hidden',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.3)',
  },
  progressBar: {
    backgroundColor: '#fff',
    height: '100%',
    position: 'absolute',
    left: 0,
    top: 0,
  },
  progressText: {
    fontSize: 9,
    fontWeight: '900',
    color: '#FF5E62',
    textAlign: 'center',
    width: '100%',
    textShadowColor: 'white',
    textShadowRadius: 1,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    padding: 20,
    paddingTop: 5,
  },
  recipesGrid: {
    flexDirection: 'column',
  },
  recipeCard: {
    backgroundColor: 'white',
    borderRadius: 16,
    paddingTop: 10,
    paddingBottom: 0,
    marginBottom: 10,
    width: '100%',
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  recipeTitleContainer: {
    alignItems: 'center',
    marginBottom: 8,
  },
  recipeTitleBox: {
    backgroundColor: 'white',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 300,
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  recipeName: {
    fontSize: 14,
    fontWeight: '700',
    color: '#4a4a4a',
    flex: 1,
    textAlign: 'left',
    left: 5,
    lineHeight: 16,
  },
  recipePriceContainer: {
    position: 'absolute',
    right: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
  },
  recipeIngredients: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    alignItems: 'center',
    minHeight: 50,
    marginBottom: 2,
  },
  recipeFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  recipePrice: {
    fontSize: 14,
    fontWeight: '900',
    color: '#27ae60',
  },
  recipeCoin: {
    width: 16,
    height: 16,
  },
  secretText: {
    fontSize: 20,
    fontWeight: '900',
    color: '#adb5bd',
  },
  bookPagesBg: {
    flex: 1,
    flexDirection: 'column',
    padding: 10,
  },
  bookPageLeft: {
    flex: 1,
    alignItems: 'center',
  },
  bookPageRight: {
    flex: 1,
    alignItems: 'center',
    paddingTop: 20,
  },
  bookDivider: {
    height: 2,
    backgroundColor: '#D4B483',
    width: '90%',
    alignSelf: 'center',
    marginVertical: 15,
    opacity: 0.5,
  },
  recipeDetailName: {
    fontSize: 28,
    fontWeight: '900',
    color: '#5D4037',
    textAlign: 'center',
    marginBottom: 20,
    textTransform: 'uppercase',
  },
  recipeIngredientsDetail: {
    flexDirection: 'column',
    width: '100%',
    gap: 10,
  },
  ingredientDetailItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.4)',
    padding: 8,
    borderRadius: 12,
    gap: 15,
  },
  ingredientDetailName: {
    fontSize: 16,
    fontWeight: '800',
    color: '#5D4037',
  },
  recipePriceDetail: {
    alignItems: 'center',
    marginBottom: 20,
  },
  priceLabel: {
    fontSize: 12,
    fontWeight: '900',
    color: '#A1887F',
    marginBottom: 4,
    textTransform: 'uppercase',
  },
  priceValueRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  recipePriceValue: {
    fontSize: 36,
    fontWeight: '900',
    color: '#2E7D32',
  },
  coinIcon: {
    width: 30,
    height: 30,
  },
  instructionSection: {
    backgroundColor: 'rgba(255,255,255,0.3)',
    padding: 15,
    borderRadius: 15,
    width: '100%',
  },
  instructionTitle: {
    fontSize: 14,
    fontWeight: '900',
    color: '#5D4037',
    marginBottom: 8,
  },
  recipeDescription: {
    fontSize: 13,
    color: '#6D4C41',
    textAlign: 'center',
    lineHeight: 18,
    fontStyle: 'italic',
  },
});
